apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: kube-system
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: rabbitmq
    meta.helm.sh/release-namespace: kube-system
stringData:
  username: "user"
  rabbitmq-password: "$RABBITMQ_PASSWORD"
  type: kubernetes.io/basic-auth
